version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/React-FE
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu
